### PR TITLE
Initial set up

### PR DESCRIPTION
**Pull request by petterarvidsson**

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg Initial version of the flowers plugin. Please have a look. I am not 100% pleased with the results, but let's test and tweak a bit.

**Comment by petterarvidsson** [comment]
Maybe we need more flowers?
screenshot from 2016-02-01 14 22 16

**Comment by nsg** [comment]
@petterarvidsson looks good

> Maybe we need more flowers?

Maybe make `random-growth` a range, make the flower density a little random :)

**Comment by nsg** [comment]
Still good enough for a :+1: and a merge I think, we can tweak the rest later :)

**Pull request merged**
